import { useState, useEffect, useMemo, useRef } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { 
  Calendar, 
  Download, 
  Rocket, 
  Plus, 
  Trash2, 
  AlertCircle,
  ChevronDown,
  Building2,
  User,
  Link as LinkIcon,
  FileText,
  X,
  Check,
  Copy,
  Briefcase,
  GripVertical,
  Newspaper
} from 'lucide-react';
import { RichNotesEditor } from './RichNotesEditor';
import { api } from '../lib/api';

interface SumarioRow {
  id: string;
  plannedDate: string;
  canal: string;
  speakerId: string;
  pilarId: string;
  title: string;
  formatoId: string;
  copy: string;
  estadoProduccion: string;
  estadoAprobacionCliente: 'BORRADOR' | 'ENVIADO_AL_CLIENTE' | 'APROBADO' | 'RECHAZADO' | 'REQUIERE_AJUSTES';
  linkPublicacionReal: string;
  referencias: string;
  isAutoGenerated?: boolean;
  isTarea?: boolean;
  isPrensa?: boolean;
  sortOrder?: number;
}

// Genera meses desde 6 meses atrás hasta el PRÓXIMO mes relativo al actual (M + 1)
function getAvailableMonths(): { value: string; label: string }[] {
  const now = new Date();
  const currentYear = now.getFullYear();
  const currentMonth = now.getMonth();
  const nombresMeses = [
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
  ];

  const months: { value: string; label: string }[] = [];
  // Desde 6 meses atrás hasta el próximo mes (i = 1)
  for (let i = -6; i <= 1; i++) {
    const d = new Date(currentYear, currentMonth + i, 1);
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    months.push({
      value: `${y}-${m}`,
      label: `${nombresMeses[d.getMonth()]} ${y}`
    });
  }
  return months;
}

export function SumarioTab({ clientId }: { clientId: string }) {
  const queryClient = useQueryClient();

  // Opciones de períodos (hasta mes actual + 1)
  const availableMonths = useMemo(() => getAvailableMonths(), []);
  
  // Mes seleccionado (único)
  const getCurrentMonthVal = () => {
    const now = new Date();
    const y = now.getFullYear();
    const m = String(now.getMonth() + 1).padStart(2, '0');
    return `${y}-${m}`;
  };

  const [periodo, setPeriodo] = useState<string>(getCurrentMonthVal());

  // Queries reales de voceros, pilares y formatos (TicketTypes)
  const { data: speakersData } = useQuery({
    queryKey: ['speakers', clientId],
    queryFn: () => api.getSpeakers(clientId),
  });

  const { data: pilaresData } = useQuery({
    queryKey: ['pilares', clientId],
    queryFn: () => api.getPilares(clientId),
  });

  const { data: ticketTypesData } = useQuery({
    queryKey: ['ticketTypes'],
    queryFn: () => api.getTicketTypes(),
  });

  const { data: clientsData } = useQuery({
    queryKey: ['clients'],
    queryFn: () => api.getClients(),
  });

  const speakers = speakersData?.data ?? [];
  const pilares = pilaresData?.data ?? [];
  const formatos = (ticketTypesData?.data ?? []).filter((t: any) => t.kind !== 'TAREA' && t.kind !== 'PRENSA');
  const tareaFormatos = (ticketTypesData?.data ?? []).filter((t: any) => t.kind === 'TAREA');
  const prensaFormatos = (ticketTypesData?.data ?? []).filter((t: any) => t.kind === 'PRENSA');
  const client = clientsData?.data.find((c: any) => c.id === clientId);

  const monthlyTarget = client?.monthlyContentTarget ?? 12;

  // Query de los tickets del sumario
  const { data: ticketsData, isLoading: isLoadingTickets } = useQuery({
    queryKey: ['sumario-tickets', clientId, periodo],
    queryFn: () => api.getTickets({ clientId, isDraftPlan: 'all' }),
  });

  const rawTickets = ticketsData?.data ?? [];

  // Mapear los tickets del backend a nuestro SumarioRow con filtrado estricto por clientId (Fix Draper leak)
  const allRows: SumarioRow[] = rawTickets
    .filter((t: any) => {
      // Safety guard: Forzar pertenencia estricta a este cliente
      if (t.clientId && t.clientId !== clientId) return false;

      // Si la fecha de publicación está vacía (null/undefined), incluir siempre en la vista del sumario
      if (!t.plannedDate) return true;

      // Filtrado por el mes seleccionado (YYYY-MM)
      return t.plannedDate.startsWith(periodo);
    })
    .map((t: any, index: number) => {
      const isPrensa = t.ticketType?.kind === 'PRENSA' || t.area === 'PRENSA';
      const isTarea = !isPrensa && t.ticketType?.kind === 'TAREA';
      return {
        id: t.id,
        plannedDate: t.plannedDate ? t.plannedDate.substring(0, 10) : '',
        canal: t.canales?.[0] || (isPrensa ? 'Prensa' : t.ticketType?.name === 'Newsletter' ? 'Newsletter' : t.ticketType?.name === 'Blog' ? 'Blog' : 'LinkedIn'),
        speakerId: t.speakerId || '',
        pilarId: t.pilarId || '',
        formatoId: t.ticketTypeId || '',
        title: t.title || '',
        copy: t.content || '',
        isTarea,
        isPrensa,
        sortOrder: t.sortOrder ?? index,
        estadoProduccion: (() => {
          if (t.status === 'PUBLICADO' || t.status === 'LISTO_PARA_PUBLICAR' || (t.status === 'CERRADO' && t.closeReason === 'PUBLICADO')) {
            return 'Publicado';
          }
          if (t.subEstado) {
            if (['LISTO', 'PUBLICADO'].includes(t.subEstado)) return 'Publicado';
            if (['REVISION_INTERNA', 'ENVIADO_CLIENTE'].includes(t.subEstado)) return 'Diseño/Edición';
            if (t.subEstado === 'EN_CURSO') return 'Redacción';
            return 'Ideación';
          }
          if (t.status === 'REDACCION') return 'Redacción';
          if (['DISENO', 'EDICION', 'REVISION_INTERNA', 'CLIENTE', 'ESPERANDO_FEEDBACK'].includes(t.status)) return 'Diseño/Edición';
          return 'Ideación';
        })(),
        estadoAprobacionCliente: t.estadoAprobacionCliente || 'BORRADOR',
        linkPublicacionReal: t.linkEntregable || '',
        referencias: t.description || '',
        isAutoGenerated: t.keywords === 'auto_generated',
      };
    });

  // Separar Contenidos, Tareas y Prensa
  const contentRows = allRows.filter(r => !r.isTarea && !r.isPrensa);
  const tareaRows = allRows.filter(r => r.isTarea && !r.isPrensa);
  const prensaRows = allRows.filter(r => r.isPrensa);

  // Tabs por cuenta: Marca + un tab por cada vocero del cliente
  const [activeTab, setActiveTab] = useState<string>('MARCA');
  const tabs = [
    { id: 'MARCA', label: 'Marca' },
    ...speakers.map((s: any) => ({ id: s.id, label: s.nombre })),
  ];

  // Si el tab activo deja de existir (cambió el cliente), volver a Marca
  useEffect(() => {
    if (activeTab !== 'MARCA' && !speakers.some((s: any) => s.id === activeTab)) {
      setActiveTab('MARCA');
    }
  }, [speakers, activeTab]);

  // Reordenar filas (Drag and Drop / Orden manual)
  const [rowSortOrder, setRowSortOrder] = useState<Record<string, number>>({});


  // Filas visibles de contenido según el tab activo
  const tabFilteredContentRows = contentRows.filter((r) =>
    activeTab === 'MARCA' ? !r.speakerId : r.speakerId === activeTab
  );

  const rows = useMemo(() => {
    return [...tabFilteredContentRows].sort((a, b) => {
      const orderA = rowSortOrder[a.id] ?? a.sortOrder ?? 0;
      const orderB = rowSortOrder[b.id] ?? b.sortOrder ?? 0;
      return orderA - orderB;
    });
  }, [tabFilteredContentRows, rowSortOrder]);

  // Filas de tareas visibles según tab activo
  const tabFilteredTareaRows = tareaRows.filter((r) =>
    activeTab === 'MARCA' ? !r.speakerId : r.speakerId === activeTab
  );

  const sortedTareaRows = useMemo(() => {
    return [...tabFilteredTareaRows].sort((a, b) => {
      const orderA = rowSortOrder[a.id] ?? a.sortOrder ?? 0;
      const orderB = rowSortOrder[b.id] ?? b.sortOrder ?? 0;
      return orderA - orderB;
    });
  }, [tabFilteredTareaRows, rowSortOrder]);

  // Filas de prensa visibles según tab activo
  const tabFilteredPrensaRows = prensaRows.filter((r) =>
    activeTab === 'MARCA' ? !r.speakerId : r.speakerId === activeTab
  );

  const sortedPrensaRows = useMemo(() => {
    return [...tabFilteredPrensaRows].sort((a, b) => {
      const orderA = rowSortOrder[a.id] ?? a.sortOrder ?? 0;
      const orderB = rowSortOrder[b.id] ?? b.sortOrder ?? 0;
      return orderA - orderB;
    });
  }, [tabFilteredPrensaRows, rowSortOrder]);

  const isInitialized = allRows.length > 0;
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [feedback, setFeedback] = useState<{ type: 'success' | 'info'; message: string } | null>(null);

  useEffect(() => {
    setSelectedIds([]);
  }, [clientId, periodo, activeTab]);

  // Estado para el modal de edición de Copy
  const [copyEditingRowId, setCopyEditingRowId] = useState<string | null>(null);
  const [tempCopyText, setTempCopyText] = useState('');
  const [copySaveStatus, setCopySaveStatus] = useState<'saving' | 'saved' | null>(null);
  const copySaveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Mutación para actualizar la meta del cliente
  const updateTargetMutation = useMutation({
    mutationFn: (target: number) => api.updateClient(clientId, { monthlyContentTarget: target }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['clients'] });
      showFeedback('info', 'Meta mensual de contenidos actualizada.');
    }
  });

  // Mutación para crear una fila
  const sumarioKey = ['sumario-tickets', clientId, periodo];
  const createTicketMutation = useMutation({
    mutationFn: (ticket: any) => api.createTicket(ticket),
    onMutate: async (ticket: any) => {
      await queryClient.cancelQueries({ queryKey: sumarioKey });
      const previous = queryClient.getQueryData<any>(sumarioKey);
      const optimisticRow = {
        id: `temp-${Date.now()}`,
        title: ticket.title ?? '',
        description: ticket.referencias ?? '',
        clientId: ticket.clientId,
        ownerId: ticket.ownerId,
        ticketTypeId: ticket.ticketTypeId ?? null,
        pilarId: ticket.pilarId ?? null,
        speakerId: ticket.speakerId ?? null,
        status: ticket.status ?? 'PENDIENTE',
        plannedDate: ticket.plannedDate ?? null,
        isDraftPlan: ticket.isDraftPlan ?? true,
        estadoAprobacionCliente: ticket.estadoAprobacionCliente ?? 'BORRADOR',
        canales: ticket.canales ?? (ticket.canal ? [ticket.canal] : []),
        content: ticket.copy ?? '',
        linkEntregable: ticket.linkPublicacionReal ?? '',
        ticketType: null,
        keywords: null,
      };
      queryClient.setQueryData(sumarioKey, (old: any) =>
        old ? { ...old, data: [...old.data, optimisticRow] } : old
      );
      return { previous, tempId: optimisticRow.id };
    },
    onSuccess: (created: any, _ticket, context: any) => {
      queryClient.setQueryData(sumarioKey, (old: any) =>
        old
          ? { ...old, data: old.data.map((t: any) => (t.id === context.tempId ? created.data : t)) }
          : old
      );
    },
    onError: (_err, _ticket, context: any) => {
      if (context?.previous) queryClient.setQueryData(sumarioKey, context.previous);
      showFeedback('info', 'No se pudo crear la fila. Reintentá.');
    },
  });

  // Traduce los nombres de campo del sumario a los campos crudos del ticket
  const toRawPatch = (data: any) => {
    const out: any = {};
    if ('canal' in data) out.canales = data.canal ? [data.canal] : [];
    if ('canales' in data) out.canales = data.canales;
    if ('copy' in data) out.content = data.copy;
    if ('referencias' in data) out.description = data.referencias;
    if ('linkPublicacionReal' in data) out.linkEntregable = data.linkPublicacionReal;
    for (const k of ['title', 'pilarId', 'speakerId', 'ticketTypeId', 'plannedDate', 'estadoAprobacionCliente', 'subEstado']) {
      if (k in data) out[k] = data[k];
    }
    return out;
  };

  const ESTADO_PROD_TO_SUBESTADO: Record<string, string> = {
    'Ideación': 'PENDIENTE',
    'Redacción': 'EN_CURSO',
    'Diseño/Edición': 'REVISION_INTERNA',
    'Publicado': 'LISTO',
  };

  const getEstadoProduccionStyle = (estado: string) => {
    switch (estado) {
      case 'Publicado':
        return 'text-[#024fff] bg-[#024fff]/5 border-[#024fff]/20 font-bold';
      case 'Diseño/Edición':
        return 'text-purple-700 bg-purple-50 border-purple-200';
      case 'Redacción':
        return 'text-indigo-700 bg-indigo-50 border-indigo-200';
      default: // Ideación
        return 'text-gray-500 bg-gray-50 border-gray-200';
    }
  };

  const updateTicketMutation = useMutation({
    mutationFn: ({ id, data }: { id: string; data: any }) => api.updateTicket(id, data),
    onMutate: async ({ id, data }: { id: string; data: any }) => {
      await queryClient.cancelQueries({ queryKey: sumarioKey });
      const previous = queryClient.getQueryData<any>(sumarioKey);
      const patch = toRawPatch(data);
      queryClient.setQueryData(sumarioKey, (old: any) =>
        old
          ? { ...old, data: old.data.map((t: any) => (t.id === id ? { ...t, ...patch } : t)) }
          : old
      );
      return { previous };
    },
    onSuccess: (updated: any, { id }) => {
      queryClient.setQueryData(sumarioKey, (old: any) =>
        old ? { ...old, data: old.data.map((t: any) => (t.id === id ? updated.data : t)) } : old
      );
    },
    onError: (_err, _vars, context: any) => {
      if (context?.previous) queryClient.setQueryData(sumarioKey, context.previous);
    },
  });

  const deleteTicketMutation = useMutation({
    mutationFn: (id: string) => api.deleteTicket(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sumario-tickets', clientId, periodo] });
      showFeedback('info', 'Fila de sumario eliminada.');
    }
  });

  const bulkPublishMutation = useMutation({
    mutationFn: (ids: string[]) => api.bulkPublishTickets(ids),
    onSuccess: (res: any) => {
      queryClient.invalidateQueries({ queryKey: ['sumario-tickets', clientId, periodo] });
      queryClient.invalidateQueries({ queryKey: ['tickets'] });
      showFeedback('success', `🚀 ¡Plan publicado! Se han transferido ${res.count} piezas al Backlog Kanban.`);
    }
  });

  const bulkDeleteMutation = useMutation({
    mutationFn: (ids: string[]) => api.bulkDeleteTickets(ids),
    onSuccess: (res: any) => {
      queryClient.invalidateQueries({ queryKey: ['sumario-tickets', clientId, periodo] });
      setSelectedIds([]);
      showFeedback('info', `Se eliminaron ${res.count} piezas del sumario.`);
    }
  });

  const handleSelectAll = (checked: boolean) => {
    if (checked) {
      setSelectedIds(rows.map(r => r.id));
    } else {
      setSelectedIds([]);
    }
  };

  const handleToggleSelect = (id: string, checked: boolean) => {
    if (checked) {
      setSelectedIds(prev => [...prev, id]);
    } else {
      setSelectedIds(prev => prev.filter(x => x !== id));
    }
  };

  const [openPopover, setOpenPopover] = useState<'VOCEROS' | 'REDES' | null>(null);
  const [selectedTargetSpeakerIds, setSelectedTargetSpeakerIds] = useState<string[]>([]);
  const [selectedTargetChannels, setSelectedTargetChannels] = useState<string[]>([]);
  const [isBulkCopying, setIsBulkCopying] = useState(false);

  const handleBulkDelete = () => {
    if (selectedIds.length === 0) return;
    if (window.confirm(`¿Querés eliminar las ${selectedIds.length} piezas seleccionadas?`)) {
      bulkDeleteMutation.mutate(selectedIds);
    }
  };

  const handleConfirmBulkCopyVoceros = async () => {
    if (selectedIds.length === 0 || selectedTargetSpeakerIds.length === 0) return;

    setIsBulkCopying(true);
    let countCreated = 0;
    const selectedRows = allRows.filter(r => selectedIds.includes(r.id));

    try {
      for (const row of selectedRows) {
        const rawTicket = rawTickets.find((t: any) => t.id === row.id);
        
        for (const targetSpeakerId of selectedTargetSpeakerIds) {
          const actualTargetId = targetSpeakerId === 'MARCA' ? null : targetSpeakerId;
          
          await api.createTicket({
            title: row.title,
            description: row.referencias,
            clientId: clientId,
            ownerId: rawTicket?.ownerId ?? null,
            ticketTypeId: row.formatoId || null,
            pilarId: row.pilarId || null,
            speakerId: actualTargetId,
            status: 'PENDIENTE',
            plannedDate: null,
            isDraftPlan: true,
            estadoAprobacionCliente: 'BORRADOR',
            canales: [row.canal],
            content: row.copy,
            linkEntregable: row.linkPublicacionReal,
          });
          countCreated++;
        }
      }

      queryClient.invalidateQueries({ queryKey: ['sumario-tickets', clientId, periodo] });
      showFeedback('success', `¡Copias creadas! Se duplicaron ${selectedRows.length} piezas hacia ${selectedTargetSpeakerIds.length} vocero(s).`);
      setOpenPopover(null);
      setSelectedTargetSpeakerIds([]);
      setSelectedIds([]);
    } catch (err: any) {
      showFeedback('info', 'Error al duplicar las piezas.');
    } finally {
      setIsBulkCopying(false);
    }
  };

  const handleConfirmBulkCopyRedes = async () => {
    if (selectedIds.length === 0 || selectedTargetChannels.length === 0) return;

    setIsBulkCopying(true);
    let countCreated = 0;
    const selectedRows = allRows.filter(r => selectedIds.includes(r.id));

    try {
      for (const row of selectedRows) {
        const rawTicket = rawTickets.find((t: any) => t.id === row.id);
        
        for (const channel of selectedTargetChannels) {
          await api.createTicket({
            title: row.title,
            description: row.referencias,
            clientId: clientId,
            ownerId: rawTicket?.ownerId ?? null,
            ticketTypeId: row.formatoId || null,
            pilarId: row.pilarId || null,
            speakerId: activeTab === 'MARCA' ? null : activeTab,
            status: 'PENDIENTE',
            plannedDate: null,
            isDraftPlan: true,
            estadoAprobacionCliente: 'BORRADOR',
            canales: [channel],
            content: row.copy,
            linkEntregable: row.linkPublicacionReal,
          });
          countCreated++;
        }
      }

      queryClient.invalidateQueries({ queryKey: ['sumario-tickets', clientId, periodo] });
      showFeedback('success', `¡Copias creadas! Se duplicaron ${selectedRows.length} piezas hacia ${selectedTargetChannels.length} red(es).`);
      setOpenPopover(null);
      setSelectedTargetChannels([]);
      setSelectedIds([]);
    } catch (err: any) {
      showFeedback('info', 'Error al duplicar las piezas.');
    } finally {
      setIsBulkCopying(false);
    }
  };

  const handleAddRow = () => {
    createTicketMutation.mutate({
      title: '',
      clientId,
      ownerId: client?.ownerId ?? '',
      ticketTypeId: null,
      pilarId: null,
      speakerId: activeTab === 'MARCA' ? null : activeTab,
      status: 'PENDIENTE',
      plannedDate: `${periodo}-01T12:00:00.000Z`,
      isDraftPlan: true,
      estadoAprobacionCliente: 'BORRADOR',
      canal: 'LinkedIn',
      canales: ['LinkedIn'],
    });
  };

  const handleAddTareaRow = () => {
    const tareaType = tareaFormatos[0]?.id ?? null;
    createTicketMutation.mutate({
      title: '',
      clientId,
      ownerId: client?.ownerId ?? '',
      ticketTypeId: tareaType,
      pilarId: null,
      speakerId: activeTab === 'MARCA' ? null : activeTab,
      status: 'PENDIENTE',
      plannedDate: `${periodo}-01T12:00:00.000Z`,
      isDraftPlan: true,
      estadoAprobacionCliente: 'BORRADOR',
      canal: 'Tarea',
      canales: ['Tarea'],
    });
  };

  const handleAddPrensaRow = () => {
    const prensaType = prensaFormatos[0]?.id ?? null;
    createTicketMutation.mutate({
      title: '',
      clientId,
      ownerId: client?.ownerId ?? '',
      ticketTypeId: prensaType,
      area: 'PRENSA',
      pilarId: null,
      speakerId: activeTab === 'MARCA' ? null : activeTab,
      status: 'PENDIENTE',
      plannedDate: `${periodo}-01T12:00:00.000Z`,
      isDraftPlan: true,
      estadoAprobacionCliente: 'BORRADOR',
      canal: 'Prensa',
      canales: ['Prensa'],
    });
  };

  const handleDuplicateRow = async (row: SumarioRow, targetSpeakerId: string | null) => {
    const rawTicket = rawTickets.find((t: any) => t.id === row.id);
    const newTicketData = {
      title: `${row.title} (Copia)`,
      description: row.referencias,
      clientId: clientId,
      ownerId: rawTicket?.ownerId ?? null,
      ticketTypeId: row.formatoId || null,
      pilarId: row.pilarId || null,
      speakerId: targetSpeakerId,
      status: 'PENDIENTE',
      plannedDate: null,
      isDraftPlan: true,
      estadoAprobacionCliente: 'BORRADOR',
      canales: [row.canal],
      content: row.copy,
      linkEntregable: row.linkPublicacionReal,
    };

    createTicketMutation.mutate(newTicketData);
    const targetLabel = targetSpeakerId 
      ? (speakers.find((s: any) => s.id === targetSpeakerId)?.nombre ?? 'Vocero')
      : 'Marca';
    showFeedback('info', `Fila duplicada exitosamente a ${targetLabel}.`);
  };

  const handleUpdateRow = (id: string, field: string, value: any) => {
    updateTicketMutation.mutate({ id, data: { [field]: value } });
  };

  const handleDeleteRow = (id: string) => {
    if (window.confirm('¿Estás seguro de que querés eliminar esta pieza del sumario?')) {
      deleteTicketMutation.mutate(id);
    }
  };

  const handleAutoSaveCopy = (val: string) => {
    setTempCopyText(val);
    if (!copyEditingRowId) return;
    setCopySaveStatus('saving');
    if (copySaveTimeoutRef.current) clearTimeout(copySaveTimeoutRef.current);
    copySaveTimeoutRef.current = setTimeout(() => {
      handleUpdateRow(copyEditingRowId, 'copy', val);
      setCopySaveStatus('saved');
    }, 400);
  };

  const handleCloseCopyModal = () => {
    if (copySaveTimeoutRef.current) clearTimeout(copySaveTimeoutRef.current);
    if (copyEditingRowId && tempCopyText !== undefined) {
      handleUpdateRow(copyEditingRowId, 'copy', tempCopyText);
    }
    setCopySaveStatus(null);
    setCopyEditingRowId(null);
  };

  const handlePushToBacklog = () => {
    const draftIds = rawTickets
      .filter((t: any) => t.isDraftPlan && allRows.some(r => r.id === t.id))
      .map((t: any) => t.id);

    if (draftIds.length === 0) {
      showFeedback('info', 'No hay borradores pendientes de publicar en este período.');
      return;
    }

    if (window.confirm(`¿Querés publicar las ${draftIds.length} piezas borrador del sumario al Backlog Kanban de Rocky?`)) {
      bulkPublishMutation.mutate(draftIds);
    }
  };

  const handleExportToExcel = () => {
    const headers = ['Plataforma', 'Fecha de publicación', 'Pilar de contenido', 'Tema de publicación', 'Formato', 'Copy', 'Estado', 'Link audiovisual/Gráfica', 'Referencias/Info'];
    
    const rowsToExport = [...rows, ...sortedTareaRows, ...sortedPrensaRows];
    const allFormatos = [...formatos, ...tareaFormatos, ...prensaFormatos];

    const csvContent = [
      headers.join(','),
      ...rowsToExport.map(r => {
        const pilarName = pilares.find(p => p.id === r.pilarId)?.nombre ?? '';
        const formatoName = allFormatos.find(f => f.id === r.formatoId)?.name ?? '';
        return [
          `"${r.canal}"`,
          `"${r.plannedDate}"`,
          `"${pilarName}"`,
          `"${r.title.replace(/"/g, '""')}"`,
          `"${formatoName}"`,
          `"${r.copy.replace(/"/g, '""')}"`,
          `"${r.estadoProduccion}"`,
          `"${r.linkPublicacionReal}"`,
          `"${r.referencias.replace(/"/g, '""')}"`
        ].join(',');
      })
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `PLAN DE CONTENIDOS - CLIENTE - ${periodo}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    showFeedback('info', 'Excel (.csv) exportado correctamente.');
  };

  const showFeedback = (type: 'success' | 'info', message: string) => {
    setFeedback({ type, message });
    setTimeout(() => setFeedback(null), 5000);
  };

  function getPeriodoLabel(p: string) {
    const [year, month] = p.split('-');
    const nombresMeses = [
      'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
      'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
    ];
    return `${nombresMeses[parseInt(month, 10) - 1]} ${year}`;
  }

  const getCanalBadgeStyle = (canal: string) => {
    switch (canal) {
      case 'LinkedIn':
        return 'bg-[#0a66c2]/10 text-[#0a66c2] border-[#0a66c2]/25 font-bold';
      case 'Twitter/X':
        return 'bg-slate-100 text-slate-800 border-slate-300 font-bold';
      case 'Instagram':
        return 'bg-pink-50 text-pink-700 border-pink-200 font-bold';
      case 'TikTok':
        return 'bg-cyan-50 text-cyan-900 border-cyan-200 font-bold';
      case 'Blog':
        return 'bg-emerald-50 text-emerald-800 border-emerald-200 font-bold';
      case 'Newsletter':
        return 'bg-purple-50 text-purple-800 border-purple-200 font-bold';
      case 'Prensa':
        return 'bg-blue-50 text-blue-800 border-blue-200 font-bold';
      default:
        return 'bg-gray-100 text-gray-800 border-gray-200 font-bold';
    }
  };

  const PILAR_COLORS = [
    'bg-indigo-50 text-indigo-700 border-indigo-200',
    'bg-amber-50 text-amber-800 border-amber-200',
    'bg-rose-50 text-rose-700 border-rose-200',
    'bg-teal-50 text-teal-800 border-teal-200',
    'bg-violet-50 text-violet-700 border-violet-200',
  ];

  const getPilarBadgeStyle = (pilarId: string) => {
    if (!pilarId) return 'bg-gray-50 text-gray-400 border-gray-200';
    const idx = pilares.findIndex((p: any) => p.id === pilarId);
    return PILAR_COLORS[(idx >= 0 ? idx : 0) % PILAR_COLORS.length] + ' font-semibold';
  };

  // Drag and Drop de filas con mouse
  const [draggedRowId, setDraggedRowId] = useState<string | null>(null);
  const [dragOverRowId, setDragOverRowId] = useState<string | null>(null);

  const handleDragStart = (e: React.DragEvent, id: string) => {
    e.dataTransfer.setData('text/plain', id);
    e.dataTransfer.effectAllowed = 'move';
    setDraggedRowId(id);
  };

  const handleDragOver = (e: React.DragEvent, id: string) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
    if (dragOverRowId !== id) {
      setDragOverRowId(id);
    }
  };

  const handleDrop = (e: React.DragEvent, dropTargetId: string, currentCategoryRows: SumarioRow[]) => {
    e.preventDefault();
    const sourceId = e.dataTransfer.getData('text/plain') || draggedRowId;
    if (!sourceId || sourceId === dropTargetId) return;

    const sourceIndex = currentCategoryRows.findIndex(r => r.id === sourceId);
    const dropIndex = currentCategoryRows.findIndex(r => r.id === dropTargetId);
    if (sourceIndex === -1 || dropIndex === -1) return;

    const updated = [...currentCategoryRows];
    const [movedItem] = updated.splice(sourceIndex, 1);
    updated.splice(dropIndex, 0, movedItem);

    const newMap = { ...rowSortOrder };
    updated.forEach((r, idx) => {
      newMap[r.id] = idx;
    });

    setRowSortOrder(newMap);
    setDraggedRowId(null);
    setDragOverRowId(null);
  };

  const handleDragEnd = () => {
    setDraggedRowId(null);
    setDragOverRowId(null);
  };

  const renderRow = (row: SumarioRow, currentCategoryRows: SumarioRow[]) => {
    const isDragging = draggedRowId === row.id;
    const isDragOver = dragOverRowId === row.id;

    return (
      <tr
        key={row.id}
        draggable={true}
        onDragStart={(e) => handleDragStart(e, row.id)}
        onDragOver={(e) => handleDragOver(e, row.id)}
        onDrop={(e) => handleDrop(e, row.id, currentCategoryRows)}
        onDragEnd={handleDragEnd}
        className={`transition-all ${
          isDragging 
            ? 'opacity-40 bg-blue-50 border-2 border-dashed border-[#024fff]' 
            : isDragOver 
              ? 'bg-[#024fff]/10 border-t-2 border-[#024fff]' 
              : 'hover:bg-[#024fff]/[0.01]'
        }`}
      >
        {/* Checkbox de Selección */}
        <td className="w-[36px] px-2 py-2.5 text-center">
          <input
            type="checkbox"
            checked={selectedIds.includes(row.id)}
            onChange={(e) => handleToggleSelect(row.id, e.target.checked)}
            className="rounded border-[#000033]/20 text-[#024fff] focus:ring-[#024fff] cursor-pointer w-4 h-4"
          />
        </td>

        {/* Reordenar Handle Drag & Drop */}
        <td className="w-[50px] px-1 py-2.5 text-center">
          <div 
            className="flex items-center justify-center p-1 rounded hover:bg-[#000033]/5 cursor-grab active:cursor-grabbing text-[#000033]/30 hover:text-[#024fff] transition-all"
            title="Arrastrar y soltar con el mouse para reordenar"
          >
            <GripVertical className="w-4 h-4 shrink-0" />
          </div>
        </td>

      {/* Plataforma (Badge Coloreado) */}
      <td className="w-[110px] px-2 py-2.5">
        <select
          value={row.canal}
          onChange={(e) => handleUpdateRow(row.id, 'canal', e.target.value)}
          className={`w-full px-2 py-1 rounded-md border text-[11px] focus:ring-0 focus:outline-none cursor-pointer truncate ${getCanalBadgeStyle(row.canal)}`}
        >
          <option value="LinkedIn">LinkedIn</option>
          <option value="Twitter/X">Twitter/X</option>
          <option value="Instagram">Instagram</option>
          <option value="TikTok">TikTok</option>
          <option value="Newsletter">Newsletter</option>
          <option value="Blog">Blog</option>
          <option value="Prensa">Prensa</option>
        </select>
      </td>

      {/* Fecha */}
      <td className="w-[115px] px-2 py-2.5">
        <input
          type="date"
          value={row.plannedDate}
          onChange={(e) => handleUpdateRow(row.id, 'plannedDate', `${e.target.value}T12:00:00.000Z`)}
          className="w-full bg-transparent border-0 p-0 text-xs font-medium text-[#000033] focus:ring-0 focus:outline-none focus:bg-gray-50 rounded"
        />
      </td>

      {/* Pilar (Badge Coloreado) */}
      <td className="w-[120px] px-2 py-2.5">
        <select
          value={row.pilarId}
          onChange={(e) => handleUpdateRow(row.id, 'pilarId', e.target.value)}
          className={`w-full px-2 py-1 rounded-md border text-[11px] focus:ring-0 focus:outline-none cursor-pointer truncate ${getPilarBadgeStyle(row.pilarId)}`}
        >
          <option value="">Sin pilar</option>
          {pilares.map((p: any) => (
            <option key={p.id} value={p.id}>{p.nombre}</option>
          ))}
        </select>
      </td>

      {/* Tema de Publicación */}
      <td className="w-[180px] px-2 py-2.5">
        <input
          type="text"
          defaultValue={row.title}
          placeholder="Brief / Título de pieza..."
          onBlur={(e) => {
            if (e.target.value !== row.title) handleUpdateRow(row.id, 'title', e.target.value);
          }}
          className="w-full min-w-0 bg-transparent border-0 p-0 text-xs font-medium text-[#000033] placeholder-[#000033]/30 focus:ring-0 focus:outline-none focus:border-b focus:border-[#024fff] rounded truncate"
        />
      </td>

      {/* Formato */}
      <td className="w-[110px] px-2 py-2.5">
        <select
          value={row.formatoId}
          onChange={(e) => handleUpdateRow(row.id, 'ticketTypeId', e.target.value)}
          className="w-full bg-transparent border-0 p-0 text-xs text-[#000033] focus:ring-0 focus:outline-none focus:bg-gray-50 rounded cursor-pointer truncate"
        >
          <option value="">Sin formato</option>
          {(row.isPrensa ? (prensaFormatos.length > 0 ? prensaFormatos : ticketTypesData?.data ?? []) : row.isTarea ? tareaFormatos : formatos).map((f: any) => (
            <option key={f.id} value={f.id}>{f.name}</option>
          ))}
        </select>
      </td>

      {/* Copy (Vista previa chica truncada) */}
      <td className="w-[120px] px-2 py-2.5">
        <button
          type="button"
          onClick={() => {
            setCopyEditingRowId(row.id);
            setTempCopyText(row.copy);
          }}
          title={row.copy.trim() || 'Escribir copy...'}
          className={`w-full max-w-[104px] text-left truncate px-2 py-1 bg-gray-50 border border-[#000033]/8 hover:border-[#024fff]/40 rounded text-xs font-medium block h-6 overflow-hidden ${
            row.copy.trim() ? 'text-[#000033] italic' : 'text-[#000033]/35'
          }`}
        >
          {row.copy.trim() ? row.copy : 'Escribir copy...'}
        </button>
      </td>

      {/* Estado Prod. */}
      <td className="w-[115px] px-2 py-2.5">
        <select
          value={row.estadoProduccion}
          onChange={(e) => handleUpdateRow(row.id, 'subEstado', ESTADO_PROD_TO_SUBESTADO[e.target.value])}
          className={`w-full px-1.5 py-1 rounded border text-[10px] uppercase font-bold focus:outline-none focus:ring-0 cursor-pointer truncate ${getEstadoProduccionStyle(row.estadoProduccion)}`}
        >
          <option value="Ideación">Ideación</option>
          <option value="Redacción">Redacción</option>
          <option value="Diseño/Edición">Diseño/Edición</option>
          <option value="Publicado">Publicado</option>
        </select>
      </td>

      {/* Link audiovisual/Gráfica */}
      <td className="w-[130px] px-2 py-2.5">
        <div className="flex items-center gap-1 min-w-0">
          <LinkIcon className="w-3 h-3 text-[#000033]/30 shrink-0" />
          <input
            type="url"
            defaultValue={row.linkPublicacionReal}
            placeholder="Pegar link..."
            onBlur={(e) => {
              if (e.target.value !== row.linkPublicacionReal) handleUpdateRow(row.id, 'linkPublicacionReal', e.target.value);
            }}
            className="w-full min-w-0 bg-transparent border-0 p-0 text-xs text-[#024fff] font-medium placeholder-[#000033]/30 focus:ring-0 focus:outline-none focus:bg-gray-50 rounded truncate"
          />
        </div>
      </td>

      {/* Referencias/Info */}
      <td className="w-[130px] px-2 py-2.5">
        <input
          type="text"
          defaultValue={row.referencias}
          placeholder="Links o info..."
          onBlur={(e) => {
            if (e.target.value !== row.referencias) handleUpdateRow(row.id, 'referencias', e.target.value);
          }}
          className="w-full min-w-0 bg-transparent border-0 p-0 text-xs text-[#000033]/70 placeholder-[#000033]/30 focus:ring-0 focus:outline-none focus:bg-gray-50 rounded truncate"
        />
      </td>

      {/* Acciones */}
      <td className="w-[60px] px-2 py-2.5 text-center">
        <div className="flex items-center justify-center gap-1">
          <div className="relative group">
            <button
              type="button"
              title="Duplicar fila"
              className="p-1 text-[#000033]/40 hover:text-[#024fff] hover:bg-[#024fff]/5 rounded transition-all"
            >
              <Copy className="w-3.5 h-3.5" />
            </button>
            <div className="absolute right-0 top-full mt-1 hidden group-hover:block w-44 bg-white border border-[#000033]/15 rounded-lg shadow-xl z-50 p-1 text-left animate-in fade-in duration-150">
              <div className="text-[9px] font-bold uppercase text-[#000033]/40 px-2 py-1">Duplicar a...</div>
              <button
                type="button"
                onClick={() => handleDuplicateRow(row, null)}
                className="w-full text-left px-2 py-1.5 text-xs font-semibold text-[#000033] hover:bg-[#024fff]/5 hover:text-[#024fff] rounded"
              >
                🏢 Marca
              </button>
              {speakers.map((s: any) => (
                <button
                  key={s.id}
                  type="button"
                  onClick={() => handleDuplicateRow(row, s.id)}
                  className="w-full text-left px-2 py-1.5 text-xs font-semibold text-[#000033] hover:bg-[#024fff]/5 hover:text-[#024fff] rounded truncate"
                >
                  👤 {s.nombre}
                </button>
              ))}
            </div>
          </div>

          <button
            type="button"
            onClick={() => handleDeleteRow(row.id)}
            className="p-1 text-[#000033]/40 hover:text-red-500 hover:bg-red-50 rounded transition-all"
            title="Eliminar fila"
          >
            <Trash2 className="w-3.5 h-3.5" />
          </button>
        </div>
      </td>
    </tr>
  );
};

  return (
    <div className="bg-[#fafafa] min-h-screen">
      
      {/* Subheader del Sumario */}
      <div className="bg-white border-b border-[#000033]/8 px-8 py-4 sticky top-[117px] z-[15]">
        <div className="max-w-[1400px] mx-auto flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          
          {/* Selector Único de Período (Hasta mes actual + 1) */}
          <div className="flex flex-wrap items-center gap-4">
            <div className="flex items-center gap-2">
              <label className="text-[10px] font-bold uppercase tracking-wide text-[#000033]/40">Período</label>
              <div className="relative">
                <select
                  value={periodo}
                  onChange={(e) => setPeriodo(e.target.value)}
                  className="appearance-none pl-3 pr-8 py-1.5 bg-white border border-[#000033]/15 text-sm font-bold text-[#000033] rounded-lg focus:outline-none focus:border-[#024fff] cursor-pointer shadow-sm"
                >
                  {availableMonths.map((m) => (
                    <option key={m.value} value={m.value}>
                      {m.label}
                    </option>
                  ))}
                </select>
                <ChevronDown className="w-4 h-4 text-[#000033]/50 absolute right-2.5 top-2.5 pointer-events-none" />
              </div>
            </div>

            {/* Meta Mensual */}
            <div className="flex items-center gap-2 border-l border-[#000033]/10 pl-4">
              <label className="text-[10px] font-bold uppercase tracking-wide text-[#000033]/40">Meta mensual</label>
              <input
                type="number"
                min="1"
                value={monthlyTarget}
                onChange={(e) => {
                  const val = Math.max(1, parseInt(e.target.value, 10) || 1);
                  updateTargetMutation.mutate(val);
                }}
                className="w-14 px-2 py-1 bg-white border border-[#000033]/15 text-xs font-bold text-center text-[#000033] rounded-lg focus:outline-none focus:border-[#024fff]"
              />
              <span className="text-xs text-[#000033]/40 font-medium">piezas</span>
            </div>

            {isInitialized && (
              <div className="flex items-center gap-3 bg-[#024fff]/5 px-3 py-1.5 rounded-lg border border-[#024fff]/10">
                <span className="text-xs font-bold text-[#024fff]">
                  Progreso: {contentRows.length} / {monthlyTarget}
                </span>
                <div className="w-20 h-1.5 bg-[#024fff]/10 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-[#024fff] transition-all duration-300"
                    style={{ width: `${Math.min(100, (contentRows.length / monthlyTarget) * 100)}%` }}
                  />
                </div>
              </div>
            )}
          </div>

          {/* Acciones principales */}
          <div className="flex items-center gap-3">
            {isInitialized && (
              <>
                <button
                  onClick={handleExportToExcel}
                  className="flex items-center gap-2 px-3 py-2 border border-[#000033]/12 text-[#000033]/80 hover:text-[#000033] bg-white text-xs font-bold rounded-lg hover:bg-gray-50 transition-all shadow-sm"
                >
                  <Download className="w-3.5 h-3.5" />
                  Exportar Excel
                </button>
                
                <button
                  onClick={handlePushToBacklog}
                  disabled={bulkPublishMutation.isPending || !rawTickets.some((t: any) => t.isDraftPlan && allRows.some(r => r.id === t.id))}
                  className="flex items-center gap-2 px-4 py-2 bg-[#024fff] text-white text-xs font-bold rounded-lg hover:bg-[#024fff]/90 transition-all shadow-md shadow-[#024fff]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Rocket className="w-3.5 h-3.5" />
                  {bulkPublishMutation.isPending ? 'Publicando...' : 'Publicar en Backlog'}
                </button>
              </>
            )}
          </div>

        </div>
      </div>

      {/* Contenedor de Alertas */}
      {feedback && (
        <div className="max-w-[1400px] mx-auto px-8 mt-4">
          <div className={`flex items-center gap-2 px-4 py-3 rounded-lg border text-xs font-medium ${
            feedback.type === 'success' 
              ? 'bg-[#00ff99]/10 border-[#00ff99]/35 text-[#006633]' 
              : 'bg-blue-50 border-blue-200 text-blue-800'
          }`}>
            <AlertCircle className="w-4 h-4 shrink-0" />
            {feedback.message}
          </div>
        </div>
      )}

      {/* Área del Sumario */}
      <div className="max-w-[1400px] mx-auto px-8 py-6">
        
        {isLoadingTickets ? (
          <div className="flex items-center justify-center py-20 text-sm text-[#000033]/60">
            Cargando planificación...
          </div>
        ) : !isInitialized ? (
          /* Empty State */
          <div className="bg-white border-2 border-dashed border-[#000033]/12 rounded-xl p-16 flex flex-col items-center justify-center text-center max-w-[600px] mx-auto mt-10">
            <div className="w-12 h-12 rounded-full bg-[#024fff]/5 flex items-center justify-center text-[#024fff] mb-4">
              <Calendar className="w-6 h-6" />
            </div>
            <h3 className="text-sm font-bold text-[#000033] mb-1">Sin sumario activo para este período</h3>
            <p className="text-xs text-[#000033]/50 mb-6 max-w-[340px]">
              Comenzá a planificar {getPeriodoLabel(periodo)} agregando tu primera fila de contenido y completando las celdas a mano.
            </p>
            <div className="flex gap-3">
              <button
                onClick={handleAddRow}
                disabled={createTicketMutation.isPending}
                className="flex items-center gap-2 px-4 py-2.5 bg-[#024fff] text-white text-xs font-bold rounded-lg hover:bg-[#024fff]/90 transition-all shadow-md shadow-[#024fff]/10 disabled:opacity-50"
              >
                <Plus className="w-3.5 h-3.5" />
                Agregar primera fila
              </button>
            </div>
          </div>
        ) : (
          /* Tablas de Planificación */
          <div className="space-y-8">
            
            {/* Tabs por cuenta: Marca + Voceros */}
            <div className="flex flex-wrap items-center gap-1 border-b border-[#000033]/8">
              {tabs.map((tab) => {
                const count = contentRows.filter((r) =>
                  tab.id === 'MARCA' ? !r.speakerId : r.speakerId === tab.id
                ).length;
                const isActive = activeTab === tab.id;
                return (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`flex items-center gap-2 px-4 py-2.5 text-xs font-bold border-b-2 -mb-px whitespace-nowrap transition-all ${
                      isActive
                        ? 'border-[#024fff] text-[#024fff]'
                        : 'border-transparent text-[#000033]/45 hover:text-[#000033]/70'
                    }`}
                  >
                    {tab.id === 'MARCA' ? <Building2 className="w-3.5 h-3.5" /> : <User className="w-3.5 h-3.5" />}
                    {tab.label}
                    <span className={`px-1.5 py-0.5 rounded-full text-[10px] ${
                      isActive ? 'bg-[#024fff]/10 text-[#024fff]' : 'bg-[#000033]/5 text-[#000033]/40'
                    }`}>
                      {count}
                    </span>
                  </button>
                );
              })}
            </div>

            {/* Acciones Masivas */}
            {selectedIds.length > 0 && (
              <div className="bg-[#024fff]/5 border border-[#024fff]/20 rounded-xl px-4 py-2.5 flex flex-col sm:flex-row items-center justify-between gap-3 animate-in fade-in slide-in-from-top-2 duration-200">
                <div className="flex items-center gap-2">
                  <div className="w-5 h-5 rounded-full bg-[#024fff] text-white flex items-center justify-center text-[10px] font-bold">
                    {selectedIds.length}
                  </div>
                  <span className="text-xs font-bold text-[#000033]">
                    {selectedIds.length === 1 ? 'pieza seleccionada' : 'piezas seleccionadas'}
                  </span>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  {/* BOTÓN 1: COPIAR A VOCERO(S) */}
                  <div className="relative">
                    <button
                      type="button"
                      onClick={() => {
                        setOpenPopover(openPopover === 'VOCEROS' ? null : 'VOCEROS');
                        setSelectedTargetSpeakerIds([]);
                      }}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-[#024fff]/5 border border-[#024fff]/30 text-[#024fff] text-xs font-bold rounded-lg transition-all shadow-sm"
                    >
                      <User className="w-3.5 h-3.5" />
                      Copiar a Vocero(s)
                    </button>

                    {openPopover === 'VOCEROS' && (
                      <div className="absolute right-0 bottom-full mb-2 w-60 bg-white border border-[#000033]/15 rounded-xl shadow-2xl z-50 p-3 text-left animate-in fade-in zoom-in-95 duration-150">
                        <div className="text-[10px] font-bold uppercase tracking-wider text-[#024fff] mb-2">
                          Copiar a Voceros ({selectedTargetSpeakerIds.length})
                        </div>
                        <div className="space-y-1.5 max-h-48 overflow-y-auto mb-3 pr-1">
                          {activeTab !== 'MARCA' && (
                            <label className="flex items-center gap-2 px-2 py-1.5 hover:bg-[#024fff]/5 rounded cursor-pointer text-xs font-semibold text-[#000033]">
                              <input
                                type="checkbox"
                                checked={selectedTargetSpeakerIds.includes('MARCA')}
                                onChange={(e) => {
                                  if (e.target.checked) setSelectedTargetSpeakerIds(prev => [...prev, 'MARCA']);
                                  else setSelectedTargetSpeakerIds(prev => prev.filter(x => x !== 'MARCA'));
                                }}
                                className="rounded text-[#024fff] focus:ring-[#024fff]"
                              />
                              🏢 Marca
                            </label>
                          )}
                          {speakers.map((s: any) => (
                            <label key={s.id} className="flex items-center gap-2 px-2 py-1.5 hover:bg-[#024fff]/5 rounded cursor-pointer text-xs font-semibold text-[#000033] truncate">
                              <input
                                type="checkbox"
                                checked={selectedTargetSpeakerIds.includes(s.id)}
                                onChange={(e) => {
                                  if (e.target.checked) setSelectedTargetSpeakerIds(prev => [...prev, s.id]);
                                  else setSelectedTargetSpeakerIds(prev => prev.filter(x => x !== s.id));
                                }}
                                className="rounded text-[#024fff] focus:ring-[#024fff]"
                              />
                              👤 {s.nombre}
                            </label>
                          ))}

                          {speakers.length === 0 && activeTab === 'MARCA' && (
                            <p className="text-[11px] italic text-[#000033]/40 text-center py-2">
                              Sin voceros creados.
                            </p>
                          )}
                        </div>
                        <div className="flex items-center justify-end gap-2 pt-2 border-t border-[#000033]/10">
                          <button
                            type="button"
                            onClick={() => setOpenPopover(null)}
                            className="text-xs font-bold text-[#000033]/50 hover:text-[#000033] px-2 py-1"
                          >
                            Cancelar
                          </button>
                          <button
                            type="button"
                            disabled={selectedTargetSpeakerIds.length === 0 || isBulkCopying}
                            onClick={handleConfirmBulkCopyVoceros}
                            className="px-3 py-1 bg-[#024fff] text-white text-xs font-bold rounded-md hover:bg-[#024fff]/90 transition-all disabled:opacity-50"
                          >
                            {isBulkCopying ? 'Copiar...' : 'Copiar'}
                          </button>
                        </div>
                      </div>
                    )}
                  </div>

                  {/* BOTÓN 2: COPIAR A RED(ES) */}
                  <div className="relative">
                    <button
                      type="button"
                      onClick={() => {
                        setOpenPopover(openPopover === 'REDES' ? null : 'REDES');
                        setSelectedTargetChannels([]);
                      }}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-white hover:bg-[#024fff]/5 border border-[#024fff]/30 text-[#024fff] text-xs font-bold rounded-lg transition-all shadow-sm"
                    >
                      <Copy className="w-3.5 h-3.5" />
                      Copiar a Red(es)
                    </button>

                    {openPopover === 'REDES' && (
                      <div className="absolute right-0 bottom-full mb-2 w-60 bg-white border border-[#000033]/15 rounded-xl shadow-2xl z-50 p-3 text-left animate-in fade-in zoom-in-95 duration-150">
                        <div className="text-[10px] font-bold uppercase tracking-wider text-[#024fff] mb-2">
                          Copiar a Redes ({selectedTargetChannels.length})
                        </div>
                        <div className="space-y-1.5 max-h-48 overflow-y-auto mb-3 pr-1">
                          {[
                            { id: 'LinkedIn', label: 'LinkedIn' },
                            { id: 'Twitter/X', label: 'Twitter / X' },
                            { id: 'Instagram', label: 'Instagram' },
                            { id: 'TikTok', label: 'TikTok' },
                            { id: 'Blog', label: 'Blog & Artículos' },
                            { id: 'Newsletter', label: 'Newsletters' },
                          ].map(ch => (
                            <label key={ch.id} className="flex items-center gap-2 px-2 py-1.5 hover:bg-[#024fff]/5 rounded cursor-pointer text-xs font-semibold text-[#000033]">
                              <input
                                type="checkbox"
                                checked={selectedTargetChannels.includes(ch.id)}
                                onChange={(e) => {
                                  if (e.target.checked) setSelectedTargetChannels(prev => [...prev, ch.id]);
                                  else setSelectedTargetChannels(prev => prev.filter(x => x !== ch.id));
                                }}
                                className="rounded text-[#024fff] focus:ring-[#024fff]"
                              />
                              {ch.label}
                            </label>
                          ))}
                        </div>
                        <div className="flex items-center justify-end gap-2 pt-2 border-t border-[#000033]/10">
                          <button
                            type="button"
                            onClick={() => setOpenPopover(null)}
                            className="text-xs font-bold text-[#000033]/50 hover:text-[#000033] px-2 py-1"
                          >
                            Cancelar
                          </button>
                          <button
                            type="button"
                            disabled={selectedTargetChannels.length === 0 || isBulkCopying}
                            onClick={handleConfirmBulkCopyRedes}
                            className="px-3 py-1 bg-[#024fff] text-white text-xs font-bold rounded-md hover:bg-[#024fff]/90 transition-all disabled:opacity-50"
                          >
                            {isBulkCopying ? 'Copiar...' : 'Copiar'}
                          </button>
                        </div>
                      </div>
                    )}
                  </div>

                  <button
                    type="button"
                    onClick={handleBulkDelete}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-red-50 hover:bg-red-100 border border-red-200 text-red-700 text-xs font-bold rounded-lg transition-all"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                    Eliminar
                  </button>
                  <button
                    type="button"
                    onClick={() => setSelectedIds([])}
                    className="text-xs font-bold text-[#000033]/50 hover:text-[#000033] px-2 py-1"
                  >
                    Cancelar
                  </button>
                </div>
              </div>
            )}

            {/* TABLA PRINCIPAL: CONTENIDOS PUBLICABLES */}
            <div className="bg-white border border-[#000033]/12 rounded-xl overflow-hidden shadow-sm">
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse table-fixed min-w-[1220px]">
                  <thead>
                    <tr className="bg-[#fafafa] border-b border-[#000033]/10 text-[10px] font-bold uppercase tracking-wider text-[#000033]/40">
                      <th className="w-[36px] px-2 py-3 text-center">
                        <input
                          type="checkbox"
                          checked={rows.length > 0 && selectedIds.length === rows.length}
                          ref={input => {
                            if (input) {
                              input.indeterminate = selectedIds.length > 0 && selectedIds.length < rows.length;
                            }
                          }}
                          onChange={(e) => handleSelectAll(e.target.checked)}
                          className="rounded border-[#000033]/20 text-[#024fff] focus:ring-[#024fff] cursor-pointer w-4 h-4"
                        />
                      </th>
                      <th className="w-[50px] px-1 py-3 text-center font-semibold">Orden</th>
                      <th className="w-[110px] px-2 py-3 font-semibold">Plataforma</th>
                      <th className="w-[115px] px-2 py-3 font-semibold">Fecha Pub.</th>
                      <th className="w-[120px] px-2 py-3 font-semibold">Pilar</th>
                      <th className="w-[180px] px-2 py-3 font-semibold">Tema de Publicación</th>
                      <th className="w-[110px] px-2 py-3 font-semibold">Formato</th>
                      <th className="w-[120px] px-2 py-3 font-semibold">Copy</th>
                      <th className="w-[115px] px-2 py-3 font-semibold">Estado Prod.</th>
                      <th className="w-[130px] px-2 py-3 font-semibold">Link Drive</th>
                      <th className="w-[130px] px-2 py-3 font-semibold">Referencias</th>
                      <th className="w-[60px] px-2 py-3 text-center font-semibold">Acciones</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#000033]/8 text-xs text-[#000033]/80">
                    {(() => {
                      const allCategories = [
                        { key: 'LinkedIn', label: 'LinkedIn', items: rows.filter(r => r.canal === 'LinkedIn') },
                        { key: 'Twitter/X', label: 'Twitter / X', items: rows.filter(r => r.canal === 'Twitter/X') },
                        { key: 'Instagram', label: 'Instagram', items: rows.filter(r => r.canal === 'Instagram') },
                        { key: 'TikTok', label: 'TikTok', items: rows.filter(r => r.canal === 'TikTok') },
                        { key: 'Blog', label: 'Blog & Artículos', items: rows.filter(r => r.canal === 'Blog') },
                        { key: 'Newsletter', label: 'Newsletters', items: rows.filter(r => r.canal === 'Newsletter') },
                        { key: 'Otros', label: 'Otros Canales', items: rows.filter(r => !['LinkedIn', 'Twitter/X', 'Instagram', 'TikTok', 'Blog', 'Newsletter'].includes(r.canal)) },
                      ];

                      const activeCategories = allCategories.filter(cat => cat.items.length > 0);

                      if (activeCategories.length === 0) {
                        return (
                          <tr>
                            <td colSpan={12} className="px-6 py-4 text-xs italic text-[#000033]/40 text-center">
                              Sin contenidos de redes sociales o blog planificados para este mes.
                            </td>
                          </tr>
                        );
                      }

                      return activeCategories.flatMap(cat => [
                        <tr key={`cat-${cat.key}`} className="bg-[#024fff]/[0.03] border-y border-[#000033]/10">
                          <td colSpan={12} className="px-4 py-2 text-xs font-bold text-[#024fff] tracking-wide uppercase">
                            {cat.label} ({cat.items.length})
                          </td>
                        </tr>,
                        ...cat.items.map(r => renderRow(r, cat.items))
                      ]);
                    })()}
                  </tbody>
                </table>
              </div>

              {/* Botón agregar contenido */}
              <div className="bg-[#fafafa]/50 border-t border-[#000033]/8 px-4 py-2.5 flex items-center justify-between">
                <button
                  onClick={handleAddRow}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-[#024fff] hover:text-[#024fff]/80 transition-all hover:bg-[#024fff]/5 rounded-lg"
                >
                  <Plus className="w-4 h-4" />
                  Agregar contenido
                </button>
                <div className="text-[10px] font-medium text-[#000033]/40">
                  Los cambios se guardan directamente en el backlog borrador.
                </div>
              </div>
            </div>

            {/* TABLA SECUNDARIA: TAREAS Y ENTREGABLES NO-PUBLICABLES */}
            <div className="bg-white border border-amber-200/80 rounded-xl overflow-hidden shadow-sm mt-8">
              <div className="bg-amber-500/10 px-4 py-3 border-b border-amber-200/80 flex items-center justify-between">
                <div className="flex items-center gap-2 text-amber-900 font-bold text-xs uppercase tracking-wide">
                  <Briefcase className="w-4 h-4 text-amber-600" />
                  <span>Tareas (no publicables) ({sortedTareaRows.length})</span>
                </div>
                <span className="text-[11px] text-amber-800/70 font-medium">Decks, informes, reportes, news, blogs, piezas visuales puntuales</span>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse table-fixed min-w-[1220px]">
                  <thead>
                    <tr className="bg-amber-50/50 border-b border-amber-200/50 text-[10px] font-bold uppercase tracking-wider text-amber-900/60">
                      <th className="w-[36px] px-2 py-3 text-center">
                        <input
                          type="checkbox"
                          checked={sortedTareaRows.length > 0 && selectedIds.length === sortedTareaRows.length}
                          onChange={(e) => handleSelectAll(e.target.checked)}
                          className="rounded border-amber-300 text-amber-600 focus:ring-amber-500 cursor-pointer w-4 h-4"
                        />
                      </th>
                      <th className="w-[50px] px-1 py-3 text-center font-semibold">Orden</th>
                      <th className="w-[110px] px-2 py-3 font-semibold">Tipo Tarea</th>
                      <th className="w-[115px] px-2 py-3 font-semibold">Fecha Entrega</th>
                      <th className="w-[120px] px-2 py-3 font-semibold">Pilar</th>
                      <th className="w-[180px] px-2 py-3 font-semibold">Título de Tarea / Entregable</th>
                      <th className="w-[110px] px-2 py-3 font-semibold">Formato</th>
                      <th className="w-[120px] px-2 py-3 font-semibold">Descripción</th>
                      <th className="w-[115px] px-2 py-3 font-semibold">Estado Prod.</th>
                      <th className="w-[130px] px-2 py-3 font-semibold">Link Entregable</th>
                      <th className="w-[130px] px-2 py-3 font-semibold">Referencias</th>
                      <th className="w-[60px] px-2 py-3 text-center font-semibold">Acciones</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-amber-100 text-xs text-[#000033]/80 bg-amber-50/10">
                    {sortedTareaRows.length === 0 ? (
                      <tr>
                        <td colSpan={12} className="px-6 py-4 text-xs italic text-amber-900/50 text-center">
                          Sin tareas no-publicables registradas para este mes.
                        </td>
                      </tr>
                    ) : (
                      sortedTareaRows.map(r => renderRow(r, sortedTareaRows))
                    )}
                  </tbody>
                </table>
              </div>

              {/* Botón agregar tarea */}
              <div className="bg-amber-50/30 border-t border-amber-200/50 px-4 py-2.5 flex items-center justify-between">
                <button
                  onClick={handleAddTareaRow}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-amber-800 hover:text-amber-900 transition-all hover:bg-amber-100/50 rounded-lg"
                >
                  <Plus className="w-4 h-4 text-amber-600" />
                  Agregar tarea al sumario
                </button>
              </div>
            </div>

            {/* TABLA TERCERA: TAREAS Y GESTIONES DE PRENSA (PR) */}
            <div className="bg-white border border-blue-200/80 rounded-xl overflow-hidden shadow-sm mt-8">
              <div className="bg-blue-500/10 px-4 py-3 border-b border-blue-200/80 flex items-center justify-between">
                <div className="flex items-center gap-2 text-blue-900 font-bold text-xs uppercase tracking-wide">
                  <Newspaper className="w-4 h-4 text-blue-600" />
                  <span>Tareas y Gestiones de Prensa (PR) ({sortedPrensaRows.length})</span>
                </div>
                <span className="text-[11px] text-blue-800/70 font-medium">Comunicados, notas de prensa, pitches, entrevistas y gestión de medios</span>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse table-fixed min-w-[1220px]">
                  <thead>
                    <tr className="bg-blue-50/50 border-b border-blue-200/50 text-[10px] font-bold uppercase tracking-wider text-blue-900/60">
                      <th className="w-[36px] px-2 py-3 text-center">
                        <input
                          type="checkbox"
                          checked={sortedPrensaRows.length > 0 && selectedIds.length === sortedPrensaRows.length}
                          onChange={(e) => handleSelectAll(e.target.checked)}
                          className="rounded border-blue-300 text-blue-600 focus:ring-blue-500 cursor-pointer w-4 h-4"
                        />
                      </th>
                      <th className="w-[50px] px-1 py-3 text-center font-semibold">Orden</th>
                      <th className="w-[110px] px-2 py-3 font-semibold">Tipo Prensa</th>
                      <th className="w-[115px] px-2 py-3 font-semibold">Fecha Entrega</th>
                      <th className="w-[120px] px-2 py-3 font-semibold">Pilar</th>
                      <th className="w-[180px] px-2 py-3 font-semibold">Título / Asunto de Prensa</th>
                      <th className="w-[110px] px-2 py-3 font-semibold">Formato</th>
                      <th className="w-[120px] px-2 py-3 font-semibold">Descripción</th>
                      <th className="w-[115px] px-2 py-3 font-semibold">Estado Prod.</th>
                      <th className="w-[130px] px-2 py-3 font-semibold">Link Entregable</th>
                      <th className="w-[130px] px-2 py-3 font-semibold">Referencias</th>
                      <th className="w-[60px] px-2 py-3 text-center font-semibold">Acciones</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-blue-100 text-xs text-[#000033]/80 bg-blue-50/10">
                    {sortedPrensaRows.length === 0 ? (
                      <tr>
                        <td colSpan={12} className="px-6 py-4 text-xs italic text-blue-900/50 text-center">
                          Sin tareas de prensa (PR) registradas para este mes.
                        </td>
                      </tr>
                    ) : (
                      sortedPrensaRows.map(r => renderRow(r, sortedPrensaRows))
                    )}
                  </tbody>
                </table>
              </div>

              {/* Botón agregar tarea de prensa */}
              <div className="bg-blue-50/30 border-t border-blue-200/50 px-4 py-2.5 flex items-center justify-between">
                <button
                  onClick={handleAddPrensaRow}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-blue-800 hover:text-blue-900 transition-all hover:bg-blue-100/50 rounded-lg"
                >
                  <Plus className="w-4 h-4 text-blue-600" />
                  Agregar tarea de prensa
                </button>
              </div>
            </div>

          </div>
        )}

      </div>

      {/* MODAL / DIALOG PARA EDITAR EL COPY */}
      {copyEditingRowId && (
        <div className="fixed inset-0 bg-[#000033]/30 backdrop-blur-sm z-50 flex items-center justify-center p-4 overflow-y-auto">
          <div className="bg-white rounded-xl border-2 border-[#000033]/15 shadow-2xl w-full max-w-[600px] max-h-[90vh] overflow-hidden flex flex-col animate-in fade-in zoom-in-95 duration-200">
            {/* Header */}
            <div className="px-6 py-4 border-b border-[#000033]/8 flex items-center justify-between bg-[#fafafa] flex-shrink-0">
              <div className="flex items-center gap-3">
                <div className="flex items-center gap-2">
                  <FileText className="w-4 h-4 text-[#024fff]" />
                  <h3 className="text-sm font-bold text-[#000033] uppercase tracking-wide">Borrador del Copy / Texto</h3>
                </div>
                {copySaveStatus === 'saving' && (
                  <span className="text-xs font-bold text-[#024fff] flex items-center gap-1.5 animate-pulse">
                    <span className="w-2 h-2 rounded-full bg-[#024fff]" />
                    Guardando…
                  </span>
                )}
                {copySaveStatus === 'saved' && (
                  <span className="text-xs font-bold text-emerald-600 flex items-center gap-1">
                    <Check className="w-3.5 h-3.5" />
                    Guardado
                  </span>
                )}
              </div>
              <button
                onClick={handleCloseCopyModal}
                className="p-1 hover:bg-[#000033]/5 text-[#000033]/60 hover:text-[#000033] rounded-lg transition-all"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
            
            {/* Body */}
            <div className="p-6 flex-1 min-h-0 overflow-y-auto">
              <label className="text-[10px] font-bold uppercase tracking-wide text-[#000033]/40 block mb-2">
                Texto de la publicación / Descripción de tarea
              </label>
              <RichNotesEditor
                value={tempCopyText}
                onChange={handleAutoSaveCopy}
                onBlur={handleCloseCopyModal}
                placeholder="Escribí o formateá el texto completo acá..."
                minHeight="160px"
                maxHeight="320px"
              />
            </div>

            {/* Footer */}
            <div className="px-6 py-3 bg-[#fafafa] border-t border-[#000033]/8 flex justify-between items-center flex-shrink-0">
              <span className="text-xs text-[#000033]/40 italic">Se guarda automáticamente al escribir</span>
              <button
                type="button"
                onClick={handleCloseCopyModal}
                className="px-4 py-2 bg-[#024fff] text-white text-xs font-bold rounded-lg hover:bg-[#024fff]/90 transition-all shadow-md shadow-[#024fff]/10"
              >
                Listo
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
