import { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { 
  Calendar, 
  Download, 
  Rocket, 
  Plus, 
  Trash2, 
  AlertCircle,
  ChevronDown,
  Building2,
  User,
  Link as LinkIcon,
  FileText,
  X,
  Check
} from 'lucide-react';
import { api } from '../lib/api';

interface SumarioRow {
  id: string;
  plannedDate: string;
  canal: string;
  speakerId: string;
  pilarId: string;
  title: string;
  formatoId: string;
  copy: string;
  estadoProduccion: string;
  estadoAprobacionCliente: 'BORRADOR' | 'ENVIADO_AL_CLIENTE' | 'APROBADO' | 'RECHAZADO' | 'REQUIERE_AJUSTES';
  linkPublicacionReal: string;
  referencias: string;
  isAutoGenerated?: boolean;
}

export function SumarioTab({ clientId }: { clientId: string }) {
  const queryClient = useQueryClient();

  // Query reales de voceros, pilares y formatos (TicketTypes)
  const { data: speakersData } = useQuery({
    queryKey: ['speakers', clientId],
    queryFn: () => api.getSpeakers(clientId),
  });

  const { data: pilaresData } = useQuery({
    queryKey: ['pilares', clientId],
    queryFn: () => api.getPilares(clientId),
  });

  const { data: ticketTypesData } = useQuery({
    queryKey: ['ticketTypes'],
    queryFn: () => api.getTicketTypes(),
  });

  const { data: clientsData } = useQuery({
    queryKey: ['clients'],
    queryFn: () => api.getClients(),
  });

  const speakers = speakersData?.data ?? [];
  const pilares = pilaresData?.data ?? [];
  const formatos = (ticketTypesData?.data ?? []).filter((t: any) => t.kind !== 'TAREA');
  const client = clientsData?.data.find((c: any) => c.id === clientId);

  // Configuración de período
  const [periodo, setPeriodo] = useState('2026-06');
  const monthlyTarget = client?.monthlyContentTarget ?? 12;

  // Query de los tickets reales planificados del sumario
  const { data: ticketsData, isLoading: isLoadingTickets } = useQuery({
    queryKey: ['sumario-tickets', clientId, periodo],
    queryFn: () => api.getTickets({ clientId, isDraftPlan: 'all' }),
  });

  const rawTickets = ticketsData?.data ?? [];

  // Mapear los tickets del backend a nuestro SumarioRow
  const allRows: SumarioRow[] = rawTickets
    .filter((t: any) => {
      // Excluir tareas
      if (t.ticketType?.kind === 'TAREA') return false;

      // Determinar la fecha de referencia para el mes (priorizando plannedDate, luego dueDate, luego createdAt)
      const dateToUse = t.plannedDate || t.dueDate || t.createdAt;
      return dateToUse && dateToUse.startsWith(periodo);
    })
    .map((t: any) => ({
      id: t.id,
      plannedDate: t.plannedDate ? t.plannedDate.substring(0, 10) : '',
      canal: t.canales?.[0] || 'LinkedIn',
      speakerId: t.speakerId || '',
      pilarId: t.pilarId || '',
      formatoId: t.ticketTypeId || '',
      title: t.title || '',
      copy: t.content || '',
      estadoProduccion: (() => {
        if (t.status === 'PUBLICADO' || t.status === 'LISTO_PARA_PUBLICAR' || (t.status === 'CERRADO' && t.closeReason === 'PUBLICADO')) {
          return 'Publicado';
        }
        if (t.subEstado) {
          if (['A_PUBLICAR', 'LISTO', 'PUBLICADO'].includes(t.subEstado)) return 'Publicado';
          if (['REVISION_INTERNA', 'ENVIADO_CLIENTE'].includes(t.subEstado)) return 'Diseño/Edición';
          if (t.subEstado === 'EN_CURSO') return 'Redacción';
          return 'Ideación';
        }
        if (t.status === 'REDACCION') return 'Redacción';
        if (['DISENO', 'EDICION', 'REVISION_INTERNA', 'CLIENTE', 'ESPERANDO_FEEDBACK'].includes(t.status)) return 'Diseño/Edición';
        return 'Ideación';
      })(),
      estadoAprobacionCliente: t.estadoAprobacionCliente || 'BORRADOR',
      linkPublicacionReal: t.linkEntregable || '',
      referencias: t.description || '',
      isAutoGenerated: t.keywords === 'auto_generated',
    }));

  // Tabs por cuenta: Marca + un tab por cada vocero del cliente
  const [activeTab, setActiveTab] = useState<string>('MARCA');
  const tabs = [
    { id: 'MARCA', label: 'Marca' },
    ...speakers.map((s: any) => ({ id: s.id, label: s.nombre })),
  ];

  // Si el tab activo deja de existir (cambió el cliente), volver a Marca
  useEffect(() => {
    if (activeTab !== 'MARCA' && !speakers.some((s: any) => s.id === activeTab)) {
      setActiveTab('MARCA');
    }
  }, [speakers, activeTab]);

  // Filas visibles según el tab activo (Marca = contenido sin vocero asignado)
  const rows = allRows.filter((r) =>
    activeTab === 'MARCA' ? !r.speakerId : r.speakerId === activeTab
  );

  const isInitialized = allRows.length > 0;
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [feedback, setFeedback] = useState<{ type: 'success' | 'info'; message: string } | null>(null);

  useEffect(() => {
    setSelectedIds([]);
  }, [clientId, periodo, activeTab]);

  // Estado para el modal de edición de Copy
  const [copyEditingRowId, setCopyEditingRowId] = useState<string | null>(null);
  const [tempCopyText, setTempCopyText] = useState('');

  // Mutación para actualizar la meta del cliente
  const updateTargetMutation = useMutation({
    mutationFn: (target: number) => api.updateClient(clientId, { monthlyContentTarget: target }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['clients'] });
      showFeedback('info', 'Meta mensual de contenidos actualizada.');
    }
  });

  // Mutación para crear una fila (con optimistic update: la fila aparece al instante)
  const sumarioKey = ['sumario-tickets', clientId, periodo];
  const createTicketMutation = useMutation({
    mutationFn: (ticket: any) => api.createTicket(ticket),
    onMutate: async (ticket: any) => {
      await queryClient.cancelQueries({ queryKey: sumarioKey });
      const previous = queryClient.getQueryData<any>(sumarioKey);
      const optimisticRow = {
        id: `temp-${Date.now()}`,
        title: ticket.title ?? '',
        description: ticket.referencias ?? '',
        clientId: ticket.clientId,
        ownerId: ticket.ownerId,
        ticketTypeId: ticket.ticketTypeId ?? null,
        pilarId: ticket.pilarId ?? null,
        speakerId: ticket.speakerId ?? null,
        status: ticket.status ?? 'PENDIENTE',
        plannedDate: ticket.plannedDate ?? null,
        isDraftPlan: ticket.isDraftPlan ?? true,
        estadoAprobacionCliente: ticket.estadoAprobacionCliente ?? 'BORRADOR',
        canales: ticket.canales ?? (ticket.canal ? [ticket.canal] : []),
        content: ticket.copy ?? '',
        linkEntregable: ticket.linkPublicacionReal ?? '',
        ticketType: null,
        keywords: null,
      };
      queryClient.setQueryData(sumarioKey, (old: any) =>
        old ? { ...old, data: [...old.data, optimisticRow] } : old
      );
      return { previous };
    },
    onError: (_err, _ticket, context: any) => {
      if (context?.previous) queryClient.setQueryData(sumarioKey, context.previous);
      showFeedback('info', 'No se pudo crear la fila. Reintentá.');
    },
    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: sumarioKey });
    },
  });

  // Traduce los nombres de campo del sumario a los campos crudos del ticket
  const toRawPatch = (data: any) => {
    const out: any = {};
    if ('canal' in data) out.canales = data.canal ? [data.canal] : [];
    if ('canales' in data) out.canales = data.canales;
    if ('copy' in data) out.content = data.copy;
    if ('referencias' in data) out.description = data.referencias;
    if ('linkPublicacionReal' in data) out.linkEntregable = data.linkPublicacionReal;
    for (const k of ['title', 'pilarId', 'speakerId', 'ticketTypeId', 'plannedDate', 'estadoAprobacionCliente', 'subEstado']) {
      if (k in data) out[k] = data[k];
    }
    return out;
  };

  // Mapeo Estado de Producción (label visible) -> subEstado real del ticket
  const ESTADO_PROD_TO_SUBESTADO: Record<string, string> = {
    'Ideación': 'PENDIENTE',
    'Redacción': 'EN_CURSO',
    'Diseño/Edición': 'REVISION_INTERNA',
    'Publicado': 'LISTO',
  };

  const getEstadoProduccionStyle = (estado: string) => {
    switch (estado) {
      case 'Publicado':
        return 'text-[#024fff] bg-[#024fff]/5 border-[#024fff]/20 font-bold';
      case 'Diseño/Edición':
        return 'text-purple-700 bg-purple-50 border-purple-200';
      case 'Redacción':
        return 'text-indigo-700 bg-indigo-50 border-indigo-200';
      default: // Ideación
        return 'text-gray-500 bg-gray-50 border-gray-200';
    }
  };

  // Mutación para actualizar un campo de la fila (optimista: refleja el cambio al instante)
  const updateTicketMutation = useMutation({
    mutationFn: ({ id, data }: { id: string; data: any }) => api.updateTicket(id, data),
    onMutate: async ({ id, data }: { id: string; data: any }) => {
      await queryClient.cancelQueries({ queryKey: sumarioKey });
      const previous = queryClient.getQueryData<any>(sumarioKey);
      const patch = toRawPatch(data);
      queryClient.setQueryData(sumarioKey, (old: any) =>
        old
          ? { ...old, data: old.data.map((t: any) => (t.id === id ? { ...t, ...patch } : t)) }
          : old
      );
      return { previous };
    },
    onError: (_err, _vars, context: any) => {
      if (context?.previous) queryClient.setQueryData(sumarioKey, context.previous);
    },
    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: sumarioKey });
    },
  });

  // Mutación para eliminar un ticket
  const deleteTicketMutation = useMutation({
    mutationFn: (id: string) => api.deleteTicket(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sumario-tickets', clientId, periodo] });
      showFeedback('info', 'Fila de sumario eliminada.');
    }
  });

  // Mutación para publicar sumario al backlog (Sumario -> Backlog)
  const bulkPublishMutation = useMutation({
    mutationFn: (ids: string[]) => api.bulkPublishTickets(ids),
    onSuccess: (res: any) => {
      queryClient.invalidateQueries({ queryKey: ['sumario-tickets', clientId, periodo] });
      queryClient.invalidateQueries({ queryKey: ['tickets'] });
      showFeedback('success', `🚀 ¡Plan publicado! Se han transferido ${res.count} piezas al Backlog Kanban.`);
    }
  });

  // Mutación para eliminar en lote (bulk delete)
  const bulkDeleteMutation = useMutation({
    mutationFn: (ids: string[]) => api.bulkDeleteTickets(ids),
    onSuccess: (res: any) => {
      queryClient.invalidateQueries({ queryKey: ['sumario-tickets', clientId, periodo] });
      setSelectedIds([]);
      showFeedback('info', `Se eliminaron ${res.count} piezas del sumario.`);
    }
  });

  // Handlers para selección y acciones masivas
  const handleSelectAll = (checked: boolean) => {
    if (checked) {
      setSelectedIds(rows.map(r => r.id));
    } else {
      setSelectedIds([]);
    }
  };

  const handleToggleSelect = (id: string, checked: boolean) => {
    if (checked) {
      setSelectedIds(prev => [...prev, id]);
    } else {
      setSelectedIds(prev => prev.filter(x => x !== id));
    }
  };

  const handleBulkDelete = () => {
    if (selectedIds.length === 0) return;
    if (window.confirm(`¿Querés eliminar las ${selectedIds.length} piezas seleccionadas?`)) {
      bulkDeleteMutation.mutate(selectedIds);
    }
  };

  const handleAddRow = () => {
    createTicketMutation.mutate({
      title: '',
      clientId,
      ownerId: client?.ownerId ?? '',
      ticketTypeId: null,
      pilarId: null,
      // La fila hereda la cuenta del tab activo (Marca = sin vocero)
      speakerId: activeTab === 'MARCA' ? null : activeTab,
      status: 'PENDIENTE',
      plannedDate: `${periodo}-01T12:00:00.000Z`,
      isDraftPlan: true,
      estadoAprobacionCliente: 'BORRADOR',
      canal: 'LinkedIn',
      canales: ['LinkedIn'],
    });
  };

  const handleUpdateRow = (id: string, field: string, value: any) => {
    updateTicketMutation.mutate({ id, data: { [field]: value } });
  };

  const handleDeleteRow = (id: string) => {
    if (window.confirm('¿Estás seguro de que querés eliminar esta pieza del sumario?')) {
      deleteTicketMutation.mutate(id);
    }
  };

  // Guardar el copy editado desde el modal
  const handleSaveCopy = () => {
    if (copyEditingRowId) {
      handleUpdateRow(copyEditingRowId, 'copy', tempCopyText);
      setCopyEditingRowId(null);
      showFeedback('info', 'Texto del copy actualizado.');
    }
  };

  // Publicar semana/mes al backlog
  const handlePushToBacklog = () => {
    const draftIds = rawTickets
      .filter((t: any) => t.isDraftPlan && allRows.some(r => r.id === t.id))
      .map((t: any) => t.id);

    if (draftIds.length === 0) {
      showFeedback('info', 'No hay borradores pendientes de publicar en este período.');
      return;
    }

    if (window.confirm(`¿Querés publicar las ${draftIds.length} piezas borrador del sumario al Backlog Kanban de Rocky?`)) {
      bulkPublishMutation.mutate(draftIds);
    }
  };

  // Exportar a Excel
  const handleExportToExcel = () => {
    const headers = ['Plataforma', 'Fecha de publicación', 'Pilar de contenido', 'Tema de publicación', 'Formato', 'Copy', 'Estado', 'Link audiovisual/Gráfica', 'Referencias/Info'];
    
    const csvContent = [
      headers.join(','),
      ...rows.map(r => {
        const pilarName = pilares.find(p => p.id === r.pilarId)?.nombre ?? '';
        const formatoName = formatos.find(f => f.id === r.formatoId)?.name ?? '';
        return [
          `"${r.canal}"`,
          `"${r.plannedDate}"`,
          `"${pilarName}"`,
          `"${r.title.replace(/"/g, '""')}"`,
          `"${formatoName}"`,
          `"${r.copy.replace(/"/g, '""')}"`,
          `"${r.estadoProduccion}"`,
          `"${r.linkPublicacionReal}"`,
          `"${r.referencias.replace(/"/g, '""')}"`
        ].join(',');
      })
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `PLAN DE CONTENIDOS - CLIENTE - ${periodo}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    showFeedback('info', 'Excel (.csv) exportado correctamente.');
  };

  const showFeedback = (type: 'success' | 'info', message: string) => {
    setFeedback({ type, message });
    setTimeout(() => setFeedback(null), 5000);
  };

  function getPeriodoLabel(p: string) {
    const [year, month] = p.split('-');
    const nombresMeses = [
      'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
      'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
    ];
    return `${nombresMeses[parseInt(month, 10) - 1]} ${year}`;
  }

  return (
    <div className="bg-[#fafafa] min-h-screen">
      
      {/* Subheader del Sumario */}
      <div className="bg-white border-b border-[#000033]/8 px-8 py-4 sticky top-[117px] z-[5]">
        <div className="max-w-[1400px] mx-auto flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          
          {/* Controles de Período y Volumen */}
          <div className="flex flex-wrap items-center gap-4">
            <div className="flex items-center gap-2">
              <label className="text-[10px] font-bold uppercase tracking-wide text-[#000033]/40">Período</label>
              <div className="relative">
                <select
                  value={periodo}
                  onChange={(e) => setPeriodo(e.target.value)}
                  className="appearance-none pl-3 pr-8 py-1.5 bg-white border border-[#000033]/15 text-sm font-bold text-[#000033] rounded-lg focus:outline-none focus:border-[#024fff]"
                >
                  <option value="2026-05">Mayo 2026</option>
                  <option value="2026-06">Junio 2026</option>
                  <option value="2026-07">Julio 2026</option>
                </select>
                <ChevronDown className="w-4 h-4 text-[#000033]/50 absolute right-2.5 top-2.5 pointer-events-none" />
              </div>
            </div>

            <div className="flex items-center gap-2">
              <label className="text-[10px] font-bold uppercase tracking-wide text-[#000033]/40">Meta mensual</label>
              <input
                type="number"
                min="1"
                value={monthlyTarget}
                onChange={(e) => {
                  const val = Math.max(1, parseInt(e.target.value, 10) || 1);
                  updateTargetMutation.mutate(val);
                }}
                className="w-16 px-2 py-1.5 bg-white border border-[#000033]/15 text-sm font-bold text-center text-[#000033] rounded-lg focus:outline-none focus:border-[#024fff]"
              />
              <span className="text-xs text-[#000033]/40 font-medium">piezas</span>
            </div>

            {isInitialized && (
              <div className="flex items-center gap-3 bg-[#024fff]/5 px-3 py-1.5 rounded-lg border border-[#024fff]/10">
                <span className="text-xs font-bold text-[#024fff]">
                  Progreso: {allRows.length} / {monthlyTarget}
                </span>
                <div className="w-24 h-1.5 bg-[#024fff]/10 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-[#024fff] transition-all duration-300"
                    style={{ width: `${Math.min(100, (allRows.length / monthlyTarget) * 100)}%` }}
                  />
                </div>
              </div>
            )}
          </div>

          {/* Acciones principales */}
          <div className="flex items-center gap-3">
            {isInitialized && (
              <>
                <button
                  onClick={handleExportToExcel}
                  className="flex items-center gap-2 px-3 py-2 border border-[#000033]/12 text-[#000033]/80 hover:text-[#000033] bg-white text-xs font-bold rounded-lg hover:bg-gray-50 transition-all"
                >
                  <Download className="w-3.5 h-3.5" />
                  Exportar Excel
                </button>
                
                <button
                  onClick={handlePushToBacklog}
                  disabled={bulkPublishMutation.isPending || !rawTickets.some((t: any) => t.isDraftPlan && allRows.some(r => r.id === t.id))}
                  className="flex items-center gap-2 px-4 py-2 bg-[#024fff] text-white text-xs font-bold rounded-lg hover:bg-[#024fff]/90 transition-all shadow-md shadow-[#024fff]/10 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Rocket className="w-3.5 h-3.5" />
                  {bulkPublishMutation.isPending ? 'Publicando...' : 'Publicar en Backlog'}
                </button>
              </>
            )}
          </div>

        </div>
      </div>

      {/* Contenedor de Alertas */}
      {feedback && (
        <div className="max-w-[1400px] mx-auto px-8 mt-4">
          <div className={`flex items-center gap-2 px-4 py-3 rounded-lg border text-xs font-medium ${
            feedback.type === 'success' 
              ? 'bg-[#00ff99]/10 border-[#00ff99]/35 text-[#006633]' 
              : 'bg-blue-50 border-blue-200 text-blue-800'
          }`}>
            <AlertCircle className="w-4 h-4 shrink-0" />
            {feedback.message}
          </div>
        </div>
      )}

      {/* Área del Sumario */}
      <div className="max-w-[1400px] mx-auto px-8 py-6">
        
        {isLoadingTickets ? (
          <div className="flex items-center justify-center py-20 text-sm text-[#000033]/60">
            Cargando planificación...
          </div>
        ) : !isInitialized ? (
          /* Empty State */
          <div className="bg-white border-2 border-dashed border-[#000033]/12 rounded-xl p-16 flex flex-col items-center justify-center text-center max-w-[600px] mx-auto mt-10">
            <div className="w-12 h-12 rounded-full bg-[#024fff]/5 flex items-center justify-center text-[#024fff] mb-4">
              <Calendar className="w-6 h-6" />
            </div>
            <h3 className="text-sm font-bold text-[#000033] mb-1">Sin sumario activo para este período</h3>
            <p className="text-xs text-[#000033]/50 mb-6 max-w-[340px]">
              Comenzá a planificar {getPeriodoLabel(periodo)} agregando tu primera fila de contenido y completando las celdas a mano.
            </p>
            <div className="flex gap-3">
              <button
                onClick={handleAddRow}
                disabled={createTicketMutation.isPending}
                className="flex items-center gap-2 px-4 py-2.5 bg-[#024fff] text-white text-xs font-bold rounded-lg hover:bg-[#024fff]/90 transition-all shadow-md shadow-[#024fff]/10 disabled:opacity-50"
              >
                <Plus className="w-3.5 h-3.5" />
                Agregar primera fila
              </button>
            </div>
          </div>
        ) : (
          /* Tabla de Planificación */
          <div>
            {/* Tabs por cuenta: Marca + un tab por cada vocero */}
            <div className="flex items-center gap-1 mb-4 border-b border-[#000033]/8 overflow-x-auto">
              {tabs.map((tab) => {
                const count = allRows.filter((r) =>
                  tab.id === 'MARCA' ? !r.speakerId : r.speakerId === tab.id
                ).length;
                const isActive = activeTab === tab.id;
                return (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`flex items-center gap-2 px-4 py-2.5 text-xs font-bold border-b-2 -mb-px whitespace-nowrap transition-all ${
                      isActive
                        ? 'border-[#024fff] text-[#024fff]'
                        : 'border-transparent text-[#000033]/45 hover:text-[#000033]/70'
                    }`}
                  >
                    {tab.id === 'MARCA' ? <Building2 className="w-3.5 h-3.5" /> : <User className="w-3.5 h-3.5" />}
                    {tab.label}
                    <span className={`px-1.5 py-0.5 rounded-full text-[10px] ${
                      isActive ? 'bg-[#024fff]/10 text-[#024fff]' : 'bg-[#000033]/5 text-[#000033]/40'
                    }`}>
                      {count}
                    </span>
                  </button>
                );
              })}
            </div>

            {/* Acciones Masivas (Bulk Actions Bar) */}
            {selectedIds.length > 0 && (
              <div className="bg-[#024fff]/5 border border-[#024fff]/20 rounded-xl px-4 py-2.5 mb-4 flex flex-col sm:flex-row items-center justify-between gap-3 animate-in fade-in slide-in-from-top-2 duration-200">
                <div className="flex items-center gap-2">
                  <div className="w-5 h-5 rounded-full bg-[#024fff] text-white flex items-center justify-center text-[10px] font-bold">
                    {selectedIds.length}
                  </div>
                  <span className="text-xs font-bold text-[#000033]">
                    {selectedIds.length === 1 ? 'pieza seleccionada' : 'piezas seleccionadas'}
                  </span>
                </div>
                <div className="flex flex-wrap items-center gap-3">
                  <button
                    onClick={handleBulkDelete}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-red-50 hover:bg-red-100 border border-red-200 text-red-700 text-xs font-bold rounded-lg transition-all"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                    Eliminar
                  </button>

                  <button
                    onClick={() => setSelectedIds([])}
                    className="text-xs font-bold text-[#000033]/50 hover:text-[#000033] px-2 py-1"
                  >
                    Cancelar
                  </button>
                </div>
              </div>
            )}

            <div className="bg-white border border-[#000033]/12 rounded-xl overflow-hidden shadow-sm">
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse table-fixed min-w-[1560px]">
                  <thead>
                    <tr className="bg-[#fafafa] border-b border-[#000033]/10 text-[10px] font-bold uppercase tracking-wider text-[#000033]/40">
                      <th className="w-[40px] px-3 py-3 text-center">
                        <input
                          type="checkbox"
                          checked={rows.length > 0 && selectedIds.length === rows.length}
                          ref={input => {
                            if (input) {
                              input.indeterminate = selectedIds.length > 0 && selectedIds.length < rows.length;
                            }
                          }}
                          onChange={(e) => handleSelectAll(e.target.checked)}
                          className="rounded border-[#000033]/20 text-[#024fff] focus:ring-[#024fff] cursor-pointer w-4 h-4"
                        />
                      </th>
                      <th className="w-[110px] px-3 py-3 font-semibold">Plataforma</th>
                    <th className="w-[120px] px-3 py-3 font-semibold">Fecha de Pub.</th>
                    <th className="w-[150px] px-3 py-3 font-semibold">Pilar de Cont.</th>
                    <th className="px-3 py-3 font-semibold w-[220px]">Tema de Publicación</th>
                    <th className="w-[140px] px-3 py-3 font-semibold">Formato</th>
                    <th className="w-[180px] px-3 py-3 font-semibold">Copy</th>
                    <th className="w-[150px] px-3 py-3 font-semibold">Estado Prod.</th>
                    <th className="px-3 py-3 font-semibold w-[200px]">Link audiovisual/Gráfica</th>
                    <th className="px-3 py-3 font-semibold w-[200px]">Referencias/Info</th>
                    <th className="w-[50px] px-3 py-3 text-center font-semibold"></th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#000033]/8 text-xs text-[#000033]/80">
                  {rows.map((row) => (
                    <tr key={row.id} className="hover:bg-[#024fff]/[0.01] transition-all">
                      
                      {/* Checkbox de Selección */}
                      <td className="px-3 py-2.5 text-center">
                        <input
                          type="checkbox"
                          checked={selectedIds.includes(row.id)}
                          onChange={(e) => handleToggleSelect(row.id, e.target.checked)}
                          className="rounded border-[#000033]/20 text-[#024fff] focus:ring-[#024fff] cursor-pointer w-4 h-4"
                        />
                      </td>

                      {/* Plataforma */}
                      <td className="px-3 py-2.5">
                        <select
                          value={row.canal}
                          onChange={(e) => handleUpdateRow(row.id, 'canal', e.target.value)}
                          className="w-full bg-transparent border-0 p-0 text-xs font-semibold text-[#000033] focus:ring-0 focus:outline-none focus:bg-gray-50 rounded cursor-pointer"
                        >
                          <option value="LinkedIn">LinkedIn</option>
                          <option value="Twitter/X">Twitter/X</option>
                          <option value="Instagram">Instagram</option>
                          <option value="TikTok">TikTok</option>
                          <option value="Newsletter">Newsletter</option>
                          <option value="Blog">Blog</option>
                        </select>
                      </td>

                      {/* Fecha */}
                      <td className="px-3 py-2.5">
                        <input
                          type="date"
                          value={row.plannedDate}
                          onChange={(e) => handleUpdateRow(row.id, 'plannedDate', `${e.target.value}T12:00:00.000Z`)}
                          className="w-full bg-transparent border-0 p-0 text-xs font-medium text-[#000033] focus:ring-0 focus:outline-none focus:bg-gray-50 rounded"
                        />
                      </td>

                      {/* Pilar */}
                      <td className="px-3 py-2.5">
                        <select
                          value={row.pilarId}
                          onChange={(e) => handleUpdateRow(row.id, 'pilarId', e.target.value)}
                          className="w-full bg-transparent border-0 p-0 text-xs text-[#000033] focus:ring-0 focus:outline-none focus:bg-gray-50 rounded cursor-pointer"
                        >
                          <option value="">Sin pilar</option>
                          {pilares.map((p: any) => (
                            <option key={p.id} value={p.id}>{p.nombre}</option>
                          ))}
                        </select>
                      </td>

                      {/* Tema de Publicación */}
                      <td className="px-3 py-2.5">
                        <input
                          type="text"
                          defaultValue={row.title}
                          placeholder="Brief / Título de pieza..."
                          onBlur={(e) => {
                            if (e.target.value !== row.title) handleUpdateRow(row.id, 'title', e.target.value);
                          }}
                          className="w-full min-w-0 bg-transparent border-0 p-0 text-xs font-medium text-[#000033] placeholder-[#000033]/30 focus:ring-0 focus:outline-none focus:border-b focus:border-[#024fff] rounded"
                        />
                      </td>

                      {/* Formato */}
                      <td className="px-3 py-2.5">
                        <select
                          value={row.formatoId}
                          onChange={(e) => handleUpdateRow(row.id, 'ticketTypeId', e.target.value)}
                          className="w-full bg-transparent border-0 p-0 text-xs text-[#000033] focus:ring-0 focus:outline-none focus:bg-gray-50 rounded cursor-pointer"
                        >
                          <option value="">Sin formato</option>
                          {formatos.map((f: any) => (
                            <option key={f.id} value={f.id}>{f.name}</option>
                          ))}
                        </select>
                      </td>

                      {/* Copy */}
                      <td className="px-3 py-2.5">
                        <button
                          onClick={() => {
                            setCopyEditingRowId(row.id);
                            setTempCopyText(row.copy);
                          }}
                          className={`w-full text-left truncate px-2 py-1 bg-gray-50 border border-[#000033]/8 hover:border-[#024fff]/40 rounded text-xs font-medium block h-6 ${
                            row.copy.trim() ? 'text-[#000033] italic' : 'text-[#000033]/35'
                          }`}
                        >
                          {row.copy.trim() ? row.copy : 'Escribir copy...'}
                        </button>
                      </td>

                      {/* Estado Prod. */}
                      <td className="px-3 py-2.5">
                        <select
                          value={row.estadoProduccion}
                          onChange={(e) => handleUpdateRow(row.id, 'subEstado', ESTADO_PROD_TO_SUBESTADO[e.target.value])}
                          className={`px-2 py-1 rounded border text-[10px] uppercase font-bold focus:outline-none focus:ring-0 cursor-pointer ${getEstadoProduccionStyle(row.estadoProduccion)}`}
                        >
                          <option value="Ideación">Ideación</option>
                          <option value="Redacción">Redacción</option>
                          <option value="Diseño/Edición">Diseño/Edición</option>
                          <option value="Publicado">Publicado</option>
                        </select>
                      </td>

                      {/* Link audiovisual/Gráfica */}
                      <td className="px-3 py-2.5 flex items-center gap-1.5">
                        <LinkIcon className="w-3.5 h-3.5 text-[#000033]/30 shrink-0" />
                        <input
                          type="url"
                          defaultValue={row.linkPublicacionReal}
                          placeholder="Pegar link de Drive..."
                          onBlur={(e) => {
                            if (e.target.value !== row.linkPublicacionReal) handleUpdateRow(row.id, 'linkPublicacionReal', e.target.value);
                          }}
                          className="w-full bg-transparent border-0 p-0 text-xs text-[#024fff] font-medium placeholder-[#000033]/30 focus:ring-0 focus:outline-none focus:bg-gray-50 rounded"
                        />
                      </td>

                      {/* Referencias/Info */}
                      <td className="px-3 py-2.5">
                        <input
                          type="text"
                          defaultValue={row.referencias}
                          placeholder="Links o info..."
                          onBlur={(e) => {
                            if (e.target.value !== row.referencias) handleUpdateRow(row.id, 'referencias', e.target.value);
                          }}
                          className="w-full bg-transparent border-0 p-0 text-xs text-[#000033]/70 placeholder-[#000033]/30 focus:ring-0 focus:outline-none focus:bg-gray-50 rounded"
                        />
                      </td>

                      {/* Acciones */}
                      <td className="px-3 py-2.5 text-center">
                        <button
                          onClick={() => handleDeleteRow(row.id)}
                          className="p-1 text-[#000033]/40 hover:text-red-500 hover:bg-red-50 rounded transition-all"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </td>

                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Fila inferior para agregar contenido */}
            <div className="bg-[#fafafa]/50 border-t border-[#000033]/8 px-4 py-2.5 flex items-center justify-between">
              <button
                onClick={handleAddRow}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-[#024fff] hover:text-[#024fff]/80 transition-all hover:bg-[#024fff]/5 rounded-lg"
              >
                <Plus className="w-4 h-4" />
                Agregar contenido
              </button>
              
              <div className="text-[10px] font-medium text-[#000033]/40">
                Los cambios se guardan directamente en el backlog borrador.
              </div>
            </div>

          </div>
        </div>
      )}

      </div>

      {/* MODAL / DIALOG PARA EDITAR EL COPY */}
      {copyEditingRowId && (
        <div className="fixed inset-0 bg-[#000033]/30 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl border-2 border-[#000033]/15 shadow-2xl w-full max-w-[600px] overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            {/* Header */}
            <div className="px-6 py-4 border-b border-[#000033]/8 flex items-center justify-between bg-[#fafafa]">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-[#024fff]" />
                <h3 className="text-sm font-bold text-[#000033] uppercase tracking-wide">Borrador del Copy</h3>
              </div>
              <button
                onClick={() => setCopyEditingRowId(null)}
                className="p-1 hover:bg-[#000033]/5 text-[#000033]/60 hover:text-[#000033] rounded-lg transition-all"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
            
            {/* Body */}
            <div className="p-6">
              <label className="text-[10px] font-bold uppercase tracking-wide text-[#000033]/40 block mb-2">
                Texto de la publicación (LinkedIn / Twitter)
              </label>
              <textarea
                value={tempCopyText}
                onChange={(e) => setTempCopyText(e.target.value)}
                placeholder="Escribí el texto completo del copy acá..."
                rows={10}
                className="w-full p-4 border border-[#000033]/15 rounded-lg focus:outline-none focus:border-[#024fff] text-xs font-mono leading-relaxed bg-[#fafafa] focus:bg-white transition-all text-[#000033]"
              />
            </div>

            {/* Footer */}
            <div className="px-6 py-4 bg-[#fafafa] border-t border-[#000033]/8 flex justify-end gap-3">
              <button
                onClick={() => setCopyEditingRowId(null)}
                className="px-4 py-2 border border-[#000033]/12 text-[#000033]/70 hover:text-[#000033] bg-white text-xs font-bold rounded-lg hover:bg-gray-50 transition-all"
              >
                Cancelar
              </button>
              <button
                onClick={handleSaveCopy}
                className="px-4 py-2 bg-[#024fff] text-white text-xs font-bold rounded-lg hover:bg-[#024fff]/90 transition-all shadow-md shadow-[#024fff]/10 flex items-center gap-1.5"
              >
                <Check className="w-3.5 h-3.5" />
                Guardar Copy
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
